<Project Sdk="Godot.NET.Sdk/4.4.1">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SpaceCapture.Shared\SpaceCapture.Shared.csproj" />
  </ItemGroup>

</Project>